import type { Application, Company, Contact, Goals, Interview, InterviewStyle, InterviewType, NetworkingEvent, Task } from "./types";

export const companies: Company[] = [
  {
    id: "co1",
    name: "Northwind Co.",
    isTarget: true,
    status: "applied",
    industry: "Product design / SaaS",
    website: "https://northwind.co",
    locations: [{ city: "Detroit", state: "MI" }],
    notes: "Collaborative design team culture — Alex is a great internal advocate.",
  },
  {
    id: "co2",
    name: "Beacon Analytics",
    isTarget: false,
    status: "researching",
    locations: [],
    notes: "",
  },
  {
    id: "co3",
    name: "Cedar Grove Health",
    isTarget: false,
    status: "researching",
    locations: [],
    notes: "",
  },
  {
    id: "co4",
    name: "Fathom Robotics",
    isTarget: true,
    status: "applied",
    industry: "Robotics",
    website: "https://fathomrobotics.com",
    locations: [{ city: "Ann Arbor", state: "MI" }],
    notes: "Dream role — design systems + robotics. Priya and Jamie are both great contacts here.",
  },
  {
    id: "co5",
    name: "Lumen Studio",
    isTarget: false,
    status: "researching",
    locations: [],
    notes: "",
  },
  {
    id: "co6",
    name: "Anchor Systems",
    isTarget: false,
    status: "researching",
    locations: [],
    notes: "",
  },
  {
    id: "co7",
    name: "Harborlight Media",
    isTarget: true,
    status: "applied",
    industry: "Media & publishing",
    website: "https://harborlightmedia.com",
    locations: [{ city: "Chicago", state: "IL" }],
    notes: "",
  },
  {
    id: "co8",
    name: "Solstice Financial",
    isTarget: false,
    status: "researching",
    locations: [],
    notes: "",
  },
  {
    id: "co9",
    name: "Pinehurst Studio",
    isTarget: false,
    status: "researching",
    locations: [],
    notes: "",
  },
  {
    id: "co10",
    name: "Vantage Robotics",
    isTarget: true,
    status: "watching",
    industry: "Robotics",
    website: "https://vantagerobotics.com",
    locations: [{ city: "Southfield", state: "MI" }],
    notes: "Jordan offered to refer me — waiting on an updated resume before applying.",
  },
  {
    id: "co11",
    name: "Meridian Health",
    isTarget: false,
    status: "researching",
    locations: [],
    notes: "",
  },
  {
    id: "co12",
    name: "Solera Dynamics",
    isTarget: true,
    status: "researching",
    industry: "Climate tech",
    website: "https://soleradynamics.com",
    locations: [{ city: "Portland", state: "OR" }],
    notes: "Series C climate tech startup — reached out to their recruiter on LinkedIn, waiting to hear about an open PM Design role.",
  },
  {
    id: "co13",
    name: "Cobalt Interactive",
    isTarget: true,
    status: "watching",
    industry: "Gaming & entertainment",
    website: "https://cobaltinteractive.com",
    locations: [
      { city: "Austin", state: "TX" },
      { city: "San Francisco", state: "CA" },
    ],
    notes: "Keeping an eye on their careers page — no open design roles yet.",
  },
  {
    id: "co14",
    name: "TechNova Inc",
    isTarget: false,
    status: "applied",
    industry: "SaaS",
    website: "https://technova.io",
    locations: [{ city: "Austin", state: "TX" }],
    notes: "",
  },
  {
    id: "co15",
    name: "Quantum Systems",
    isTarget: false,
    status: "applied",
    industry: "Fintech",
    website: "https://quantumsystems.com",
    locations: [{ city: "New York", state: "NY" }],
    notes: "",
  },
  {
    id: "co16",
    name: "BrightPath Learning",
    isTarget: false,
    status: "applied",
    industry: "Edtech",
    website: "https://brightpathlearning.com",
    locations: [],
    notes: "",
  },
  {
    id: "co17",
    name: "Rivermark Data",
    isTarget: false,
    status: "applied",
    industry: "Data infrastructure",
    website: "https://rivermarkdata.com",
    locations: [{ city: "Seattle", state: "WA" }],
    notes: "",
  },
  {
    id: "co18",
    name: "Orbit Cloud",
    isTarget: true,
    status: "applied",
    industry: "Cloud infrastructure",
    website: "https://orbitcloud.dev",
    locations: [],
    notes: "",
  },
  {
    id: "co19",
    name: "Nimbus Health",
    isTarget: false,
    status: "researching",
    industry: "Healthtech",
    website: "https://nimbushealth.com",
    locations: [{ city: "Boston", state: "MA" }],
    notes: "",
  },
  {
    id: "co20",
    name: "Cascade Robotics",
    isTarget: false,
    status: "applied",
    industry: "Robotics",
    website: "https://cascaderobotics.com",
    locations: [{ city: "Pittsburgh", state: "PA" }],
    notes: "",
  },
  {
    id: "co21",
    name: "Vertex Analytics",
    isTarget: true,
    status: "applied",
    industry: "Data & AI",
    website: "https://vertexanalytics.ai",
    locations: [{ city: "San Francisco", state: "CA" }],
    notes: "",
  },
  {
    id: "co22",
    name: "Ironclad Security",
    isTarget: false,
    status: "applied",
    industry: "Security",
    website: "https://ironcladsecurity.io",
    locations: [],
    notes: "",
  },
  {
    id: "co23",
    name: "Waypoint Logistics",
    isTarget: false,
    status: "applied",
    industry: "Logistics tech",
    website: "https://waypointlogistics.com",
    locations: [{ city: "Chicago", state: "IL" }],
    notes: "",
  },
  {
    id: "co25",
    name: "Driftwood Games",
    isTarget: false,
    status: "applied",
    industry: "Gaming",
    website: "https://driftwoodgames.com",
    locations: [{ city: "Austin", state: "TX" }],
    notes: "",
  },
  {
    id: "co26",
    name: "Basecamp Retail",
    isTarget: false,
    status: "applied",
    industry: "E-commerce",
    website: "https://basecampretail.com",
    locations: [],
    notes: "",
  },
  {
    id: "co27",
    name: "Anchor Fintech",
    isTarget: false,
    status: "applied",
    industry: "Fintech",
    website: "https://anchorfintech.com",
    locations: [{ city: "New York", state: "NY" }],
    notes: "",
  },
  {
    id: "co28",
    name: "Skyline Mobile",
    isTarget: false,
    status: "researching",
    industry: "Mobile apps",
    website: "https://skylinemobile.com",
    locations: [{ city: "Denver", state: "CO" }],
    notes: "",
  },
];

export const contacts: Contact[] = [
  {
    id: "c1",
    name: "Alex Chen",
    email: "alex@northwind.co",
    companyId: "co1",
    role: "Product Design",
    notes: "On the design team at Northwind. Referred me to the Product Designer role.",
  },
  {
    id: "c2",
    name: "Priya Nair",
    email: "priya@fathomrobotics.com",
    companyId: "co4",
    role: "Engineering Manager",
    notes: "Referred me to the Design Systems Lead role. Great signal on interview loop timing.",
  },
  {
    id: "c3",
    name: "Jamie Osei",
    email: "talent@fathomrobotics.com",
    companyId: "co4",
    role: "Recruiter",
    notes: "",
  },
  {
    id: "c4",
    name: "Sam Lee",
    companyId: "co7",
    role: "Content Lead",
    notes: "Referred me to the Content Designer role.",
  },
  {
    id: "c5",
    name: "Jordan A.",
    companyId: "co10",
    role: "Product Design",
    notes: "Offered to refer me to Vantage Robotics — need an updated resume first.",
  },
  {
    id: "c6",
    name: "Morgan Reyes",
    linkedInUrl: "https://linkedin.com/in/morganreyes",
    role: "Former manager",
    notes: "Former manager, now doing independent consulting. Good for general career advice.",
  },
];

export const networkingEvents: NetworkingEvent[] = [
  {
    id: "ne1",
    contactIds: ["c1"],
    type: "Coffee chat",
    date: "Jun 20, 2026",
    applicationId: "1",
    notes: "Caught up on how the interview loop is going.",
  },
  {
    id: "ne2",
    contactIds: ["c6"],
    type: "Video call",
    date: "Jul 5, 2026",
    notes: "Quarterly catch-up — talked about the broader job market and design leadership roles.",
  },
  {
    id: "ne3",
    contactIds: ["c2", "c3"],
    type: "In-person meetup",
    date: "Jun 30, 2026",
    applicationId: "4",
    notes: "Grabbed coffee near their office after the onsite. Good signal on offer timeline.",
  },
];

export const applications: Application[] = [
  {
    id: "1",
    companyId: "co1",
    role: "Product Designer",
    dateApplied: "Jun 10, 2026",
    link: "https://northwind.co/careers/1234",
    referral: true,
    referredByContactId: "c1",
    notes: "Referral from Alex on the design team. Culture seems collaborative.",
    jobDescription: "",
    status: "interviewing",
    logo: "N",
    salaryMin: 115000,
    salaryMax: 140000,
    workArrangement: "hybrid",
    city: "Detroit",
    state: "MI",
    statusHistory: [
      { status: "applied", at: "Jun 10, 2026" },
      { status: "interviewing", at: "Jun 18, 2026" },
    ],
    interviews: [
      { id: "iv1", type: "Recruiter Screen", date: "Jun 18, 2026", notes: "30 min with recruiter, mostly logistics." },
      {
        id: "iv2",
        type: "Technical Interview",
        date: "Jul 2, 2026",
        style: "Whiteboarding",
        categories: ["System Design"],
        questionsAsked: "Portfolio review + a whiteboard exercise designing a component library.",
        notes: "Went well, good back-and-forth on tradeoffs.",
      },
    ],
    followUps: [
      { id: "fu1", date: "Jun 25, 2026", contactId: "c1", notes: "Checked in on timeline." },
    ],
  },
  {
    id: "2",
    companyId: "co2",
    role: "Senior Frontend Engineer",
    dateApplied: "Jul 10, 2026",
    link: "https://beacon.io/jobs/sfe",
    referral: false,
    notes: "Found via job board.",
    jobDescription: "",
    status: "applied",
    logo: "B",
    workArrangement: "remote",
    statusHistory: [{ status: "applied", at: "Jul 10, 2026" }],
    interviews: [],
    followUps: [],
  },
  {
    id: "3",
    companyId: "co3",
    role: "UX Researcher",
    dateApplied: "Jun 2, 2026",
    link: "",
    referral: false,
    notes: "",
    jobDescription: "",
    status: "rejected_no_interview",
    logo: "C",
    statusHistory: [
      { status: "applied", at: "Jun 2, 2026" },
      { status: "rejected_no_interview", at: "Jun 15, 2026" },
    ],
    interviews: [],
    followUps: [],
    feedback: {
      text: "Went with a candidate who had more direct healthcare research experience.",
      date: "Jun 18, 2026",
    },
  },
  {
    id: "4",
    companyId: "co4",
    role: "Design Systems Lead",
    dateApplied: "May 20, 2026",
    link: "https://fathomrobotics.com/careers/dsl",
    referral: true,
    referredByContactId: "c2",
    notes: "Dream role — design systems + robotics.",
    jobDescription: "",
    status: "offer_extended",
    logo: "F",
    salaryMin: 150000,
    salaryMax: 175000,
    workArrangement: "onsite",
    city: "Ann Arbor",
    state: "MI",
    statusHistory: [
      { status: "applied", at: "May 20, 2026" },
      { status: "interviewing", at: "May 29, 2026" },
      { status: "offer_extended", at: "Jun 28, 2026" },
    ],
    interviews: [
      { id: "iv3", type: "Recruiter Screen", date: "May 29, 2026", notes: "" },
      {
        id: "iv4",
        type: "Technical Interview",
        date: "Jun 12, 2026",
        style: "LeetCode",
        categories: ["DSA/Leetcode"],
        questionsAsked: "Implemented a rate limiter, then a debounce/throttle utility.",
        notes: "First of four back-to-back interviews — went well.",
      },
      {
        id: "iv4b",
        type: "Panel",
        date: "Jun 12, 2026",
        style: "Mixture",
        categories: ["System Design", "Behavioral"],
        questionsAsked: "Design a design-token pipeline; panel also asked about handling team conflict.",
        notes: "Panel of three — design leads + an EM.",
      },
      {
        id: "iv4c",
        type: "Behavioral",
        date: "Jun 12, 2026",
        categories: ["Behavioral"],
        notes: "Wrapped up the onsite loop with the hiring manager.",
      },
      {
        id: "iv5",
        type: "Behavioral",
        date: "Jun 20, 2026",
        categories: ["Behavioral"],
        notes: "Final round with VP Design.",
      },
    ],
    followUps: [
      { id: "fu2", date: "Jun 5, 2026", contactId: "c2", notes: "" },
      { id: "fu3", date: "Jun 22, 2026", contactId: "c3", notes: "Asked about offer timeline." },
    ],
  },
  {
    id: "5",
    companyId: "co5",
    role: "Product Designer",
    dateApplied: "May 15, 2026",
    link: "",
    referral: false,
    notes: "",
    jobDescription: "",
    status: "rejected_after_interview",
    logo: "L",
    statusHistory: [
      { status: "applied", at: "May 15, 2026" },
      { status: "interviewing", at: "May 22, 2026" },
      { status: "rejected_after_interview", at: "Jun 1, 2026" },
    ],
    interviews: [{ id: "iv6", type: "Recruiter Screen", date: "May 22, 2026", notes: "" }],
    followUps: [],
    feedback: {
      text: "Strong portfolio, but they wanted someone with deeper design systems depth for this role.",
      date: "Jun 4, 2026",
    },
  },
  {
    id: "6",
    companyId: "co6",
    role: "Staff Engineer",
    dateApplied: "Jul 8, 2026",
    link: "https://anchorsystems.com/jobs/9012",
    referral: false,
    notes: "Big comp bump if it works out.",
    jobDescription: "",
    status: "applied",
    logo: "A",
    salaryMin: 90000,
    salaryMax: 110000,
    workArrangement: "remote",
    statusHistory: [{ status: "applied", at: "Jul 8, 2026" }],
    interviews: [],
    followUps: [],
  },
  {
    id: "7",
    companyId: "co7",
    role: "Content Designer",
    dateApplied: "Jun 28, 2026",
    link: "https://harborlightmedia.com/careers",
    referral: true,
    referredByContactId: "c4",
    notes: "",
    jobDescription: "",
    status: "interviewing",
    logo: "H",
    workArrangement: "hybrid",
    city: "Chicago",
    state: "IL",
    statusHistory: [
      { status: "applied", at: "Jun 28, 2026" },
      { status: "interviewing", at: "Jul 5, 2026" },
    ],
    interviews: [{ id: "iv7", type: "Recruiter Screen", date: "Jul 5, 2026", notes: "" }],
    followUps: [],
  },
  {
    id: "8",
    companyId: "co8",
    role: "Product Designer",
    dateApplied: "Apr 30, 2026",
    link: "",
    referral: false,
    notes: "",
    jobDescription: "",
    status: "withdrawn",
    logo: "S",
    statusHistory: [
      { status: "applied", at: "Apr 30, 2026" },
      { status: "withdrawn", at: "May 10, 2026" },
    ],
    interviews: [],
    followUps: [],
  },
  {
    id: "9",
    companyId: "co9",
    role: "Design Lead",
    dateApplied: "",
    link: "https://pinehurststudio.com/careers/design-lead",
    referral: false,
    notes: "Saw this posted on a design job board — looks like a strong fit for portfolio work.",
    jobDescription: "",
    status: "todo",
    logo: "P",
    statusHistory: [{ status: "todo", at: "Jul 12, 2026" }],
    interviews: [],
    followUps: [],
  },
  {
    id: "10",
    companyId: "co10",
    role: "Product Designer",
    dateApplied: "",
    link: "",
    referral: true,
    referredByContactId: "c5",
    notes: "Jordan offered to refer me — need to get an updated resume together first.",
    jobDescription: "",
    status: "todo",
    logo: "V",
    salaryMin: 130000,
    statusHistory: [{ status: "todo", at: "Jul 13, 2026" }],
    interviews: [],
    followUps: [],
  },
  {
    id: "11",
    companyId: "co11",
    role: "UX Researcher",
    dateApplied: "",
    link: "https://meridianhealth.com/jobs/ux-researcher",
    referral: false,
    notes: "",
    jobDescription: "",
    status: "todo",
    logo: "M",
    statusHistory: [{ status: "todo", at: "Jul 14, 2026" }],
    interviews: [],
    followUps: [],
  },
  {
    id: "12",
    companyId: "co14",
    role: "Backend Engineer",
    dateApplied: "Jun 15, 2026",
    link: "https://technova.io/careers/backend",
    referral: false,
    notes: "",
    jobDescription: "",
    status: "interviewing",
    logo: "T",
    workArrangement: "remote",
    statusHistory: [
      { status: "applied", at: "Jun 15, 2026" },
      { status: "interviewing", at: "Jun 20, 2026" },
    ],
    interviews: [
      { id: "iv8", type: "Recruiter Screen", date: "Jun 20, 2026", notes: "Quick chat about the role and comp expectations." },
      {
        id: "iv9",
        type: "Technical Screen",
        date: "Jun 27, 2026",
        style: "LeetCode",
        categories: ["DSA/Leetcode"],
        questionsAsked: "Two sum variant, then a sliding window problem.",
        notes: "Solved both, good communication feedback.",
      },
    ],
    followUps: [],
  },
  {
    id: "13",
    companyId: "co15",
    role: "Senior Software Engineer",
    dateApplied: "May 5, 2026",
    link: "https://quantumsystems.com/jobs/sse",
    referral: false,
    notes: "",
    jobDescription: "",
    status: "offer_extended",
    logo: "Q",
    salaryMin: 160000,
    salaryMax: 190000,
    workArrangement: "hybrid",
    city: "New York",
    state: "NY",
    statusHistory: [
      { status: "applied", at: "May 5, 2026" },
      { status: "interviewing", at: "May 12, 2026" },
      { status: "offer_extended", at: "Jun 30, 2026" },
    ],
    interviews: [
      { id: "iv10", type: "Recruiter Screen", date: "May 12, 2026", notes: "" },
      {
        id: "iv11",
        type: "Technical Screen",
        date: "May 20, 2026",
        style: "LeetCode",
        categories: ["DSA/Leetcode"],
        questionsAsked: "Merge intervals, then an LRU cache design question.",
        notes: "",
      },
      {
        id: "iv12",
        type: "Technical Interview",
        date: "Jun 3, 2026",
        style: "Whiteboarding",
        categories: ["System Design"],
        questionsAsked: "Design a payments ledger service.",
        notes: "First of three onsite rounds.",
      },
      {
        id: "iv12b",
        type: "Panel",
        date: "Jun 3, 2026",
        style: "Mixture",
        categories: ["System Design", "Behavioral"],
        questionsAsked: "Scaling a rate limiter across regions; also asked about a time I disagreed with a PM.",
        notes: "Panel of three engineers.",
      },
      {
        id: "iv12c",
        type: "Hiring Manager",
        date: "Jun 3, 2026",
        categories: ["Behavioral"],
        notes: "Wrapped the onsite loop, talked career growth.",
      },
      {
        id: "iv13",
        type: "Hiring Manager",
        date: "Jun 10, 2026",
        categories: ["Behavioral"],
        notes: "Follow-up chat with the skip-level.",
      },
    ],
    followUps: [],
  },
  {
    id: "14",
    companyId: "co16",
    role: "Full Stack Engineer",
    dateApplied: "Jul 10, 2026",
    link: "https://brightpathlearning.com/careers",
    referral: false,
    notes: "",
    jobDescription: "",
    status: "applied",
    logo: "B",
    workArrangement: "remote",
    statusHistory: [{ status: "applied", at: "Jul 10, 2026" }],
    interviews: [],
    followUps: [],
  },
  {
    id: "15",
    companyId: "co17",
    role: "Data Engineer",
    dateApplied: "Apr 20, 2026",
    link: "https://rivermarkdata.com/jobs/data-engineer",
    referral: false,
    notes: "",
    jobDescription: "",
    status: "rejected_after_interview",
    logo: "R",
    workArrangement: "remote",
    statusHistory: [
      { status: "applied", at: "Apr 20, 2026" },
      { status: "interviewing", at: "Apr 28, 2026" },
      { status: "rejected_after_interview", at: "May 15, 2026" },
    ],
    interviews: [
      { id: "iv14", type: "Recruiter Screen", date: "Apr 28, 2026", notes: "" },
      {
        id: "iv15",
        type: "Technical Screen",
        date: "May 5, 2026",
        style: "LeetCode",
        categories: ["DSA/Leetcode", "SQL"],
        questionsAsked: "Wrote a few SQL queries with window functions, then a leetcode-style array problem.",
        notes: "",
      },
    ],
    followUps: [],
    feedback: {
      text: "Strong SQL skills but they wanted someone with more distributed systems experience.",
      date: "May 18, 2026",
    },
  },
  {
    id: "16",
    companyId: "co18",
    role: "Platform Engineer",
    dateApplied: "Jun 25, 2026",
    link: "https://orbitcloud.dev/careers/platform",
    referral: false,
    notes: "Dream infra role — they use a lot of the same tooling I already know.",
    jobDescription: "",
    status: "interviewing",
    logo: "O",
    salaryMin: 145000,
    salaryMax: 170000,
    workArrangement: "remote",
    statusHistory: [
      { status: "applied", at: "Jun 25, 2026" },
      { status: "interviewing", at: "Jul 1, 2026" },
    ],
    interviews: [
      { id: "iv16", type: "Recruiter Screen", date: "Jul 1, 2026", notes: "" },
      {
        id: "iv17",
        type: "Technical Screen",
        date: "Jul 8, 2026",
        style: "Whiteboarding",
        categories: ["System Design", "Kubernetes"],
        questionsAsked: "Whiteboarded a multi-tenant Kubernetes cluster design.",
        notes: "",
      },
    ],
    followUps: [],
  },
  {
    id: "17",
    companyId: "co19",
    role: "Software Engineer",
    dateApplied: "",
    link: "https://nimbushealth.com/careers/swe",
    referral: false,
    notes: "Saw this on a healthtech job board — worth a look.",
    jobDescription: "",
    status: "todo",
    logo: "N",
    statusHistory: [{ status: "todo", at: "Jul 15, 2026" }],
    interviews: [],
    followUps: [],
  },
  {
    id: "18",
    companyId: "co20",
    role: "Robotics Software Engineer",
    dateApplied: "Jul 3, 2026",
    link: "https://cascaderobotics.com/jobs/rse",
    referral: false,
    notes: "",
    jobDescription: "",
    status: "applied",
    logo: "C",
    workArrangement: "onsite",
    city: "Pittsburgh",
    state: "PA",
    statusHistory: [{ status: "applied", at: "Jul 3, 2026" }],
    interviews: [],
    followUps: [],
  },
  {
    id: "19",
    companyId: "co21",
    role: "ML Engineer",
    dateApplied: "Jun 1, 2026",
    link: "https://vertexanalytics.ai/careers/ml-engineer",
    referral: false,
    notes: "",
    jobDescription: "",
    status: "interviewing",
    logo: "V",
    salaryMin: 155000,
    salaryMax: 185000,
    workArrangement: "hybrid",
    city: "San Francisco",
    state: "CA",
    statusHistory: [
      { status: "applied", at: "Jun 1, 2026" },
      { status: "interviewing", at: "Jun 10, 2026" },
    ],
    interviews: [
      { id: "iv18", type: "Recruiter Screen", date: "Jun 10, 2026", notes: "" },
      {
        id: "iv19",
        type: "Technical Screen",
        date: "Jun 17, 2026",
        style: "Mixture",
        categories: ["AI/ML", "DSA/Leetcode"],
        questionsAsked: "Explained a transformer architecture, then implemented a simple gradient descent loop.",
        notes: "",
      },
      {
        id: "iv20",
        type: "Technical Interview",
        date: "Jul 5, 2026",
        style: "Other",
        categories: ["AI/ML", "Take-home/Practical"],
        questionsAsked: "Take-home model evaluation review, followed by live Q&A on tradeoffs.",
        notes: "Panel seemed impressed with the writeup.",
      },
    ],
    followUps: [],
  },
  {
    id: "20",
    companyId: "co22",
    role: "Security Engineer",
    dateApplied: "Mar 3, 2026",
    link: "",
    referral: false,
    notes: "",
    jobDescription: "",
    status: "rejected_no_interview",
    logo: "I",
    statusHistory: [
      { status: "applied", at: "Mar 3, 2026" },
      { status: "rejected_no_interview", at: "Mar 12, 2026" },
    ],
    interviews: [],
    followUps: [],
    feedback: {
      text: "Went with a candidate who had prior security clearance experience.",
      date: "Mar 14, 2026",
    },
  },
  {
    id: "21",
    companyId: "co23",
    role: "Software Engineer",
    dateApplied: "Jul 12, 2026",
    link: "https://waypointlogistics.com/careers",
    referral: false,
    notes: "",
    jobDescription: "",
    status: "applied",
    logo: "W",
    workArrangement: "onsite",
    city: "Chicago",
    state: "IL",
    statusHistory: [{ status: "applied", at: "Jul 12, 2026" }],
    interviews: [],
    followUps: [],
  },
  {
    id: "23",
    companyId: "co25",
    role: "Gameplay Engineer",
    dateApplied: "Feb 10, 2026",
    link: "",
    referral: false,
    notes: "",
    jobDescription: "",
    status: "rejected_after_interview",
    logo: "D",
    statusHistory: [
      { status: "applied", at: "Feb 10, 2026" },
      { status: "interviewing", at: "Feb 20, 2026" },
      { status: "rejected_after_interview", at: "Mar 15, 2026" },
    ],
    interviews: [
      { id: "iv25", type: "Recruiter Screen", date: "Feb 20, 2026", notes: "" },
      {
        id: "iv26",
        type: "Technical Interview",
        date: "Mar 1, 2026",
        style: "Whiteboarding",
        categories: ["DSA/Leetcode", "C++"],
        questionsAsked: "Whiteboarded a custom memory allocator; discussed frame-time optimization.",
        notes: "",
      },
    ],
    followUps: [],
    feedback: {
      text: "Solid fundamentals but they were looking for more direct game engine experience.",
      date: "Mar 18, 2026",
    },
  },
  {
    id: "24",
    companyId: "co26",
    role: "Frontend Engineer",
    dateApplied: "Jul 2, 2026",
    link: "https://basecampretail.com/careers/frontend",
    referral: false,
    notes: "",
    jobDescription: "",
    status: "interviewing",
    logo: "B",
    workArrangement: "remote",
    statusHistory: [
      { status: "applied", at: "Jul 2, 2026" },
      { status: "interviewing", at: "Jul 9, 2026" },
    ],
    interviews: [
      { id: "iv27", type: "Recruiter Screen", date: "Jul 9, 2026", notes: "" },
      {
        id: "iv28",
        type: "Technical Screen",
        date: "Jul 15, 2026",
        style: "Whiteboarding",
        categories: ["System Design", "React"],
        questionsAsked: "Built a small component with state management live, then discussed rendering performance.",
        notes: "",
      },
    ],
    followUps: [],
  },
  {
    id: "25",
    companyId: "co27",
    role: "Backend Engineer",
    dateApplied: "Jan 15, 2026",
    link: "",
    referral: false,
    notes: "",
    jobDescription: "",
    status: "offer_declined",
    logo: "A",
    salaryMin: 140000,
    salaryMax: 165000,
    workArrangement: "hybrid",
    city: "New York",
    state: "NY",
    statusHistory: [
      { status: "applied", at: "Jan 15, 2026" },
      { status: "interviewing", at: "Jan 25, 2026" },
      { status: "offer_extended", at: "Feb 20, 2026" },
      { status: "offer_declined", at: "Mar 1, 2026" },
    ],
    interviews: [
      { id: "iv29", type: "Recruiter Screen", date: "Jan 25, 2026", notes: "" },
      { id: "iv30", type: "Technical Screen", date: "Feb 1, 2026", style: "LeetCode", categories: ["DSA/Leetcode"], notes: "" },
      {
        id: "iv31",
        type: "Technical Interview",
        date: "Feb 10, 2026",
        style: "Mixture",
        categories: ["System Design", "SQL"],
        questionsAsked: "Designed a ledger reconciliation system; wrote a query to detect duplicate transactions.",
        notes: "",
      },
    ],
    followUps: [],
  },
  {
    id: "26",
    companyId: "co28",
    role: "iOS Engineer",
    dateApplied: "",
    link: "https://skylinemobile.com/careers/ios",
    referral: false,
    notes: "",
    jobDescription: "",
    status: "todo",
    logo: "S",
    statusHistory: [{ status: "todo", at: "Jul 16, 2026" }],
    interviews: [],
    followUps: [],
  },
  {
    id: "27",
    companyId: "co14",
    role: "DevOps Engineer",
    dateApplied: "Jul 14, 2026",
    link: "https://technova.io/careers/devops",
    referral: false,
    notes: "",
    jobDescription: "",
    status: "applied",
    logo: "T",
    workArrangement: "remote",
    statusHistory: [{ status: "applied", at: "Jul 14, 2026" }],
    interviews: [],
    followUps: [],
  },
  {
    id: "28",
    companyId: "co21",
    role: "Data Platform Engineer",
    dateApplied: "",
    link: "https://vertexanalytics.ai/careers/data-platform",
    referral: false,
    notes: "",
    jobDescription: "",
    status: "todo",
    logo: "V",
    statusHistory: [{ status: "todo", at: "Jul 16, 2026" }],
    interviews: [],
    followUps: [],
  },
  {
    id: "29",
    companyId: "co15",
    role: "Software Engineer",
    dateApplied: "Feb 1, 2026",
    link: "",
    referral: false,
    notes: "",
    jobDescription: "",
    status: "rejected_no_interview",
    logo: "Q",
    statusHistory: [
      { status: "applied", at: "Feb 1, 2026" },
      { status: "rejected_no_interview", at: "Feb 10, 2026" },
    ],
    interviews: [],
    followUps: [],
    feedback: {
      text: "Role was put on hold shortly after I applied.",
      date: "Feb 10, 2026",
    },
  },
  {
    id: "30",
    companyId: "co17",
    role: "Analytics Engineer",
    dateApplied: "Jul 1, 2026",
    link: "https://rivermarkdata.com/jobs/analytics-engineer",
    referral: false,
    notes: "",
    jobDescription: "",
    status: "interviewing",
    logo: "R",
    workArrangement: "remote",
    statusHistory: [
      { status: "applied", at: "Jul 1, 2026" },
      { status: "interviewing", at: "Jul 10, 2026" },
    ],
    interviews: [
      { id: "iv32", type: "Recruiter Screen", date: "Jul 10, 2026", notes: "" },
      {
        id: "iv33",
        type: "Technical Screen",
        date: "Jul 16, 2026",
        style: "LeetCode",
        categories: ["DSA/Leetcode", "SQL"],
        questionsAsked: "SQL aggregation problem plus a leetcode medium on arrays.",
        notes: "",
      },
    ],
    followUps: [],
  },
];

export const initialTasks: Task[] = [
  {
    id: "t1",
    applicationId: "2",
    dueDate: "Jul 17, 2026",
    note: "Follow up 7 days after applying",
    status: "active",
    reminderRule: { type: "days_after_applied", days: 7 },
  },
  {
    id: "t2",
    applicationId: "6",
    dueDate: "Jul 15, 2026",
    note: "Follow up 7 days after applying",
    status: "active",
    reminderRule: { type: "days_after_applied", days: 7 },
  },
  {
    id: "t3",
    applicationId: "1",
    dueDate: "Jul 9, 2026",
    note: "Check in after technical interview",
    status: "active",
    reminderRule: { type: "manual" },
  },
  {
    id: "t4",
    applicationId: "4",
    dueDate: "Jun 22, 2026",
    note: "Ask about offer timeline",
    status: "dismissed",
    reminderRule: { type: "manual" },
  },
  {
    id: "t5",
    applicationId: "7",
    dueDate: "Jul 12, 2026",
    note: "Follow up after screening call",
    status: "dismissed",
    reminderRule: { type: "manual" },
  },
];

export const initialGoals: Goals = {
  salaryMin: 120000,
  salaryMax: 150000,
  applicationsPerWeekTarget: 5,
  targetOfferDate: "Aug 15, 2026",
};

export const statusLabels: Record<Application["status"], string> = {
  todo: "To do",
  applied: "Applied",
  interviewing: "Interviewing",
  offer_extended: "Offer extended",
  offer_accepted: "Offer accepted",
  offer_declined: "Offer declined",
  rejected_no_interview: "Rejected (no interview)",
  rejected_after_interview: "Rejected (after interview)",
  withdrawn: "Withdrawn",
};

export const networkingEventTypes: string[] = [
  "Coffee chat",
  "Video call",
  "Phone call",
  "In-person meetup",
  "Conference/event",
  "Other",
];

export const statusOrder: Application["status"][] = [
  "todo",
  "applied",
  "interviewing",
  "offer_extended",
  "offer_accepted",
  "offer_declined",
  "rejected_no_interview",
  "rejected_after_interview",
  "withdrawn",
];

export const interviewTypeOptions: { value: InterviewType; label: string }[] = [
  { value: "Recruiter Screen", label: "Recruiter Screen" },
  { value: "Technical Screen", label: "Technical Screen" },
  { value: "Technical Interview", label: "Technical Interview" },
  { value: "Behavioral", label: "Behavioral" },
  { value: "Hiring Manager", label: "Hiring Manager" },
  { value: "Panel", label: "Panel" },
  { value: "Other", label: "Other" },
];

export const interviewStyleOptions: { value: InterviewStyle; label: string }[] = [
  { value: "LeetCode", label: "LeetCode" },
  { value: "Whiteboarding", label: "Whiteboarding" },
  { value: "Mixture", label: "Mixture" },
  { value: "Other", label: "Other" },
];

export const defaultInterviewCategories: string[] = [
  "Behavioral",
  "DSA/Leetcode",
  "System Design",
  "AI/ML",
  "Take-home/Practical",
  "Other",
];

/** Groups an application's interviews by date, preserving first-seen date order. Used to render "Interview day" headers when 2+ rounds share a date. */
export function groupInterviewsByDate(interviews: Interview[]): { date: string; interviews: Interview[] }[] {
  const groups: { date: string; interviews: Interview[] }[] = [];
  for (const iv of interviews) {
    const existing = groups.find((g) => g.date === iv.date);
    if (existing) existing.interviews.push(iv);
    else groups.push({ date: iv.date, interviews: [iv] });
  }
  return groups;
}
