import type { Application, Contact, Goals, NetworkingEvent, Task } from "./types";

export const contacts: Contact[] = [
  {
    id: "c1",
    name: "Alex Chen",
    email: "alex@northwind.co",
    employer: "Northwind Co.",
    role: "Product Design",
    notes: "On the design team at Northwind. Referred me to the Product Designer role.",
  },
  {
    id: "c2",
    name: "Priya Nair",
    email: "priya@fathomrobotics.com",
    employer: "Fathom Robotics",
    role: "Engineering Manager",
    notes: "Referred me to the Design Systems Lead role. Great signal on interview loop timing.",
  },
  {
    id: "c3",
    name: "Jamie Osei",
    email: "talent@fathomrobotics.com",
    employer: "Fathom Robotics",
    role: "Recruiter",
    notes: "",
  },
  {
    id: "c4",
    name: "Sam Lee",
    employer: "Harborlight Media",
    role: "Content Lead",
    notes: "Referred me to the Content Designer role.",
  },
  {
    id: "c5",
    name: "Jordan A.",
    employer: "Vantage Robotics",
    role: "Product Design",
    notes: "Offered to refer me to Vantage Robotics — need an updated resume first.",
  },
  {
    id: "c6",
    name: "Morgan Reyes",
    linkedInUrl: "https://linkedin.com/in/morganreyes",
    employer: "Indie",
    role: "Former manager",
    notes: "Former manager, now doing independent consulting. Good for general career advice.",
  },
];

export const networkingEvents: NetworkingEvent[] = [
  {
    id: "ne1",
    contactIds: ["c1"],
    type: "Coffee chat",
    date: "Jun 20, 2026",
    applicationId: "1",
    notes: "Caught up on how the interview loop is going.",
  },
  {
    id: "ne2",
    contactIds: ["c6"],
    type: "Video call",
    date: "Jul 5, 2026",
    notes: "Quarterly catch-up — talked about the broader job market and design leadership roles.",
  },
  {
    id: "ne3",
    contactIds: ["c2", "c3"],
    type: "In-person meetup",
    date: "Jun 30, 2026",
    applicationId: "4",
    notes: "Grabbed coffee near their office after the onsite. Good signal on offer timeline.",
  },
];

export const applications: Application[] = [
  {
    id: "1",
    company: "Northwind Co.",
    role: "Product Designer",
    dateApplied: "Jun 10, 2026",
    link: "https://northwind.co/careers/1234",
    referral: true,
    referredByContactId: "c1",
    notes: "Referral from Alex on the design team. Culture seems collaborative.",
    jobDescription: "",
    status: "interviewing",
    logo: "N",
    salaryMin: 115000,
    salaryMax: 140000,
    workArrangement: "hybrid",
    city: "Detroit",
    state: "MI",
    statusHistory: [
      { status: "applied", at: "Jun 10, 2026" },
      { status: "interviewing", at: "Jun 18, 2026" },
    ],
    interviews: [
      { id: "iv1", type: "Screening Call", date: "Jun 18, 2026", notes: "30 min with recruiter, mostly logistics." },
      { id: "iv2", type: "Technical Interview", date: "Jul 2, 2026", notes: "Portfolio review + whiteboard exercise." },
    ],
    followUps: [
      { id: "fu1", date: "Jun 25, 2026", contactId: "c1", notes: "Checked in on timeline." },
    ],
  },
  {
    id: "2",
    company: "Beacon Analytics",
    role: "Senior Frontend Engineer",
    dateApplied: "Jul 10, 2026",
    link: "https://beacon.io/jobs/sfe",
    referral: false,
    notes: "Found via job board.",
    jobDescription: "",
    status: "applied",
    logo: "B",
    workArrangement: "remote",
    statusHistory: [{ status: "applied", at: "Jul 10, 2026" }],
    interviews: [],
    followUps: [],
  },
  {
    id: "3",
    company: "Cedar Grove Health",
    role: "UX Researcher",
    dateApplied: "Jun 2, 2026",
    link: "",
    referral: false,
    notes: "",
    jobDescription: "",
    status: "rejected_no_interview",
    logo: "C",
    statusHistory: [
      { status: "applied", at: "Jun 2, 2026" },
      { status: "rejected_no_interview", at: "Jun 15, 2026" },
    ],
    interviews: [],
    followUps: [],
    feedback: {
      text: "Went with a candidate who had more direct healthcare research experience.",
      date: "Jun 18, 2026",
    },
  },
  {
    id: "4",
    company: "Fathom Robotics",
    role: "Design Systems Lead",
    dateApplied: "May 20, 2026",
    link: "https://fathomrobotics.com/careers/dsl",
    referral: true,
    referredByContactId: "c2",
    notes: "Dream role — design systems + robotics.",
    jobDescription: "",
    status: "offer_extended",
    logo: "F",
    salaryMin: 150000,
    salaryMax: 175000,
    workArrangement: "onsite",
    city: "Ann Arbor",
    state: "MI",
    statusHistory: [
      { status: "applied", at: "May 20, 2026" },
      { status: "interviewing", at: "May 29, 2026" },
      { status: "offer_extended", at: "Jun 28, 2026" },
    ],
    interviews: [
      { id: "iv3", type: "Screening Call", date: "May 29, 2026", notes: "" },
      { id: "iv4", type: "Onsite/Panel", date: "Jun 12, 2026", notes: "4 back-to-back interviews, went well." },
      { id: "iv5", type: "Behavioral", date: "Jun 20, 2026", notes: "Final round with VP Design." },
    ],
    followUps: [
      { id: "fu2", date: "Jun 5, 2026", contactId: "c2", notes: "" },
      { id: "fu3", date: "Jun 22, 2026", contactId: "c3", notes: "Asked about offer timeline." },
    ],
  },
  {
    id: "5",
    company: "Lumen Studio",
    role: "Product Designer",
    dateApplied: "May 15, 2026",
    link: "",
    referral: false,
    notes: "",
    jobDescription: "",
    status: "rejected_after_interview",
    logo: "L",
    statusHistory: [
      { status: "applied", at: "May 15, 2026" },
      { status: "interviewing", at: "May 22, 2026" },
      { status: "rejected_after_interview", at: "Jun 1, 2026" },
    ],
    interviews: [{ id: "iv6", type: "Screening Call", date: "May 22, 2026", notes: "" }],
    followUps: [],
    feedback: {
      text: "Strong portfolio, but they wanted someone with deeper design systems depth for this role.",
      date: "Jun 4, 2026",
    },
  },
  {
    id: "6",
    company: "Anchor Systems",
    role: "Staff Engineer",
    dateApplied: "Jul 8, 2026",
    link: "https://anchorsystems.com/jobs/9012",
    referral: false,
    notes: "Big comp bump if it works out.",
    jobDescription: "",
    status: "applied",
    logo: "A",
    salaryMin: 90000,
    salaryMax: 110000,
    workArrangement: "remote",
    statusHistory: [{ status: "applied", at: "Jul 8, 2026" }],
    interviews: [],
    followUps: [],
  },
  {
    id: "7",
    company: "Harborlight Media",
    role: "Content Designer",
    dateApplied: "Jun 28, 2026",
    link: "https://harborlightmedia.com/careers",
    referral: true,
    referredByContactId: "c4",
    notes: "",
    jobDescription: "",
    status: "interviewing",
    logo: "H",
    workArrangement: "hybrid",
    city: "Chicago",
    state: "IL",
    statusHistory: [
      { status: "applied", at: "Jun 28, 2026" },
      { status: "interviewing", at: "Jul 5, 2026" },
    ],
    interviews: [{ id: "iv7", type: "Screening Call", date: "Jul 5, 2026", notes: "" }],
    followUps: [],
  },
  {
    id: "8",
    company: "Solstice Financial",
    role: "Product Designer",
    dateApplied: "Apr 30, 2026",
    link: "",
    referral: false,
    notes: "",
    jobDescription: "",
    status: "withdrawn",
    logo: "S",
    statusHistory: [
      { status: "applied", at: "Apr 30, 2026" },
      { status: "withdrawn", at: "May 10, 2026" },
    ],
    interviews: [],
    followUps: [],
  },
  {
    id: "9",
    company: "Pinehurst Studio",
    role: "Design Lead",
    dateApplied: "",
    link: "https://pinehurststudio.com/careers/design-lead",
    referral: false,
    notes: "Saw this posted on a design job board — looks like a strong fit for portfolio work.",
    jobDescription: "",
    status: "todo",
    logo: "P",
    statusHistory: [{ status: "todo", at: "Jul 12, 2026" }],
    interviews: [],
    followUps: [],
  },
  {
    id: "10",
    company: "Vantage Robotics",
    role: "Product Designer",
    dateApplied: "",
    link: "",
    referral: true,
    referredByContactId: "c5",
    notes: "Jordan offered to refer me — need to get an updated resume together first.",
    jobDescription: "",
    status: "todo",
    logo: "V",
    salaryMin: 130000,
    statusHistory: [{ status: "todo", at: "Jul 13, 2026" }],
    interviews: [],
    followUps: [],
  },
  {
    id: "11",
    company: "Meridian Health",
    role: "UX Researcher",
    dateApplied: "",
    link: "https://meridianhealth.com/jobs/ux-researcher",
    referral: false,
    notes: "",
    jobDescription: "",
    status: "todo",
    logo: "M",
    statusHistory: [{ status: "todo", at: "Jul 14, 2026" }],
    interviews: [],
    followUps: [],
  },
];

export const initialTasks: Task[] = [
  {
    id: "t1",
    applicationId: "2",
    dueDate: "Jul 17, 2026",
    note: "Follow up 7 days after applying",
    status: "active",
    reminderRule: { type: "days_after_applied", days: 7 },
  },
  {
    id: "t2",
    applicationId: "6",
    dueDate: "Jul 15, 2026",
    note: "Follow up 7 days after applying",
    status: "active",
    reminderRule: { type: "days_after_applied", days: 7 },
  },
  {
    id: "t3",
    applicationId: "1",
    dueDate: "Jul 9, 2026",
    note: "Check in after technical interview",
    status: "active",
    reminderRule: { type: "manual" },
  },
  {
    id: "t4",
    applicationId: "4",
    dueDate: "Jun 22, 2026",
    note: "Ask about offer timeline",
    status: "dismissed",
    reminderRule: { type: "manual" },
  },
  {
    id: "t5",
    applicationId: "7",
    dueDate: "Jul 12, 2026",
    note: "Follow up after screening call",
    status: "dismissed",
    reminderRule: { type: "manual" },
  },
];

export const initialGoals: Goals = {
  salaryMin: 120000,
  salaryMax: 150000,
  applicationsPerWeekTarget: 5,
  targetOfferDate: "Aug 15, 2026",
};

export const statusLabels: Record<Application["status"], string> = {
  todo: "To do",
  applied: "Applied",
  interviewing: "Interviewing",
  offer_extended: "Offer extended",
  offer_accepted: "Offer accepted",
  offer_declined: "Offer declined",
  rejected_no_interview: "Rejected (no interview)",
  rejected_after_interview: "Rejected (after interview)",
  withdrawn: "Withdrawn",
};

export const networkingEventTypes: string[] = [
  "Coffee chat",
  "Video call",
  "Phone call",
  "In-person meetup",
  "Conference/event",
  "Other",
];

export const statusOrder: Application["status"][] = [
  "todo",
  "applied",
  "interviewing",
  "offer_extended",
  "offer_accepted",
  "offer_declined",
  "rejected_no_interview",
  "rejected_after_interview",
  "withdrawn",
];
