import type { Application, Task } from "./types";

export const applications: Application[] = [
  {
    id: "1",
    company: "Northwind Co.",
    role: "Product Designer",
    dateApplied: "Jun 10, 2026",
    link: "https://northwind.co/careers/1234",
    referral: true,
    referredBy: "Alex Chen",
    notes: "Referral from Alex on the design team. Culture seems collaborative.",
    status: "interviewing",
    logo: "N",
    statusHistory: [
      { status: "applied", at: "Jun 10, 2026" },
      { status: "interviewing", at: "Jun 18, 2026" },
    ],
    interviews: [
      { type: "Screening Call", date: "Jun 18, 2026", notes: "30 min with recruiter, mostly logistics." },
      { type: "Technical Interview", date: "Jul 2, 2026", notes: "Portfolio review + whiteboard exercise." },
    ],
    followUps: [{ date: "Jun 25, 2026", contact: "Alex Chen", info: "alex@northwind.co", notes: "Checked in on timeline." }],
  },
  {
    id: "2",
    company: "Beacon Analytics",
    role: "Senior Frontend Engineer",
    dateApplied: "Jul 10, 2026",
    link: "https://beacon.io/jobs/sfe",
    referral: false,
    notes: "Found via job board.",
    status: "applied",
    logo: "B",
    statusHistory: [{ status: "applied", at: "Jul 10, 2026" }],
    interviews: [],
    followUps: [],
  },
  {
    id: "3",
    company: "Cedar Grove Health",
    role: "UX Researcher",
    dateApplied: "Jun 2, 2026",
    link: "",
    referral: false,
    notes: "",
    status: "rejected_no_interview",
    logo: "C",
    statusHistory: [
      { status: "applied", at: "Jun 2, 2026" },
      { status: "rejected_no_interview", at: "Jun 15, 2026" },
    ],
    interviews: [],
    followUps: [],
  },
  {
    id: "4",
    company: "Fathom Robotics",
    role: "Design Systems Lead",
    dateApplied: "May 20, 2026",
    link: "https://fathomrobotics.com/careers/dsl",
    referral: true,
    referredBy: "Priya Nair",
    notes: "Dream role — design systems + robotics.",
    status: "offer_extended",
    logo: "F",
    statusHistory: [
      { status: "applied", at: "May 20, 2026" },
      { status: "interviewing", at: "May 29, 2026" },
      { status: "offer_extended", at: "Jun 28, 2026" },
    ],
    interviews: [
      { type: "Screening Call", date: "May 29, 2026", notes: "" },
      { type: "Onsite/Panel", date: "Jun 12, 2026", notes: "4 back-to-back interviews, went well." },
      { type: "Behavioral", date: "Jun 20, 2026", notes: "Final round with VP Design." },
    ],
    followUps: [
      { date: "Jun 5, 2026", contact: "Priya Nair", info: "priya@fathomrobotics.com", notes: "" },
      { date: "Jun 22, 2026", contact: "Recruiting team", info: "talent@fathomrobotics.com", notes: "Asked about offer timeline." },
    ],
  },
  {
    id: "5",
    company: "Lumen Studio",
    role: "Product Designer",
    dateApplied: "May 15, 2026",
    link: "",
    referral: false,
    notes: "",
    status: "rejected_after_interview",
    logo: "L",
    statusHistory: [
      { status: "applied", at: "May 15, 2026" },
      { status: "interviewing", at: "May 22, 2026" },
      { status: "rejected_after_interview", at: "Jun 1, 2026" },
    ],
    interviews: [{ type: "Screening Call", date: "May 22, 2026", notes: "" }],
    followUps: [],
  },
  {
    id: "6",
    company: "Anchor Systems",
    role: "Staff Engineer",
    dateApplied: "Jul 8, 2026",
    link: "https://anchorsystems.com/jobs/9012",
    referral: false,
    notes: "Big comp bump if it works out.",
    status: "applied",
    logo: "A",
    statusHistory: [{ status: "applied", at: "Jul 8, 2026" }],
    interviews: [],
    followUps: [],
  },
  {
    id: "7",
    company: "Harborlight Media",
    role: "Content Designer",
    dateApplied: "Jun 28, 2026",
    link: "https://harborlightmedia.com/careers",
    referral: true,
    referredBy: "Sam Lee",
    notes: "",
    status: "interviewing",
    logo: "H",
    statusHistory: [
      { status: "applied", at: "Jun 28, 2026" },
      { status: "interviewing", at: "Jul 5, 2026" },
    ],
    interviews: [{ type: "Screening Call", date: "Jul 5, 2026", notes: "" }],
    followUps: [],
  },
  {
    id: "8",
    company: "Solstice Financial",
    role: "Product Designer",
    dateApplied: "Apr 30, 2026",
    link: "",
    referral: false,
    notes: "",
    status: "withdrawn",
    logo: "S",
    statusHistory: [
      { status: "applied", at: "Apr 30, 2026" },
      { status: "withdrawn", at: "May 10, 2026" },
    ],
    interviews: [],
    followUps: [],
  },
];

export const initialTasks: Task[] = [
  { id: "t1", applicationId: "2", dueDate: "Jul 17, 2026", note: "Follow up 7 days after applying", status: "active" },
  { id: "t2", applicationId: "6", dueDate: "Jul 15, 2026", note: "Follow up 7 days after applying", status: "active" },
  { id: "t3", applicationId: "1", dueDate: "Jul 9, 2026", note: "Check in after technical interview", status: "active" },
  { id: "t4", applicationId: "4", dueDate: "Jun 22, 2026", note: "Ask about offer timeline", status: "dismissed" },
  { id: "t5", applicationId: "7", dueDate: "Jul 12, 2026", note: "Follow up after screening call", status: "dismissed" },
];

export const statusLabels: Record<Application["status"], string> = {
  applied: "Applied",
  interviewing: "Interviewing",
  offer_extended: "Offer extended",
  offer_accepted: "Offer accepted",
  offer_declined: "Offer declined",
  rejected_no_interview: "Rejected (no interview)",
  rejected_after_interview: "Rejected (after interview)",
  withdrawn: "Withdrawn",
};

export const statusOrder: Application["status"][] = [
  "applied",
  "interviewing",
  "offer_extended",
  "offer_accepted",
  "offer_declined",
  "rejected_no_interview",
  "rejected_after_interview",
  "withdrawn",
];
